### ISSUE TITLE
Chapter 6 - command to register meme errors out

### ISSUE THREAD

**Issue by amaharana** [NEAR-Edu/near.academy#28] opened 2022-03-02 20:49 UTC
**Describe the bug**
The command mentioned in [Chapter 6](https://near.academy/near101/chapter-6) to register a meme, fails with this error: 
```
{"ExecutionError":"Exceeded the prepaid gas."}
```

Example [failed transaction](https://explorer.testnet.near.org/transactions/BS3zmhdGYy2N4gJ1s1A9h8imBRon3z3ABodBsY8MaEoY).

**To Reproduce**
Run this command with your testnet account:
```
near call museum.testnet add_meme \
'{"meme" : "bob", "title" : "god", "data" : "https://9gag.com/gag/ad8K0vj", "category" : 4}' \
--accountId YOUR_ACCOUNT_NAME.testnet --amount 3
```

**Expected behavior**
Meme creation should succeed, [like this transaction](https://explorer.testnet.near.org/transactions/CTeV17JMwuP2xDHHTJvmdK7iRnmkBrZgwNoCiVcUX6xQ
).

**Additional context**
The command should be corrected to add gas as [clarified by Benji on Discord](https://discord.com/channels/490367152054992913/542945453533036544/912840246524260355). Working command is:
```
near call museum.testnet add_meme \
'{"meme" : "bobarana", "title" : "bobarana", "data" : "https://9gag.com/gag/ad8K0vj", "category" : 4}' \
--accountId maharana.testnet --amount 3 --gas=75000000000000
```

**Comment by ryancwalsh** [comment] 2022-03-02 20:58
Thanks for reporting this, which relates to https://github.com/NEAR-Edu/near.academy/pull/10

I wonder how this wasn't already fixed.

We'll look into it. Thanks.

**Comment by ryancwalsh** [comment] 2022-03-02 21:12
I see that the `main` branch https://github.com/NEAR-Edu/near.academy/blob/main/src/frontend/src/pages/Courses/near101/Chapters/Chapter-6/course.md does already have gas mentioned in https://github.com/NEAR-Edu/near.academy/commit/46b304dd540f77d49cc70cb21517e682ed6c30b3

So my guess is that the problem is that we're trying to migrate from one server to another, and right now the https://near.academy/ domain is pointing to the original server, whose code is presumably out of date.

We'll hopefully be switching over to the new server in the next day or so. cc @oceanByte

**Comment by oceanByte** [comment] 2022-03-09 19:56
I just deployed the newest main branch. Can you see if this problem still persists @ryancwalsh ?

**Comment by ryancwalsh** [comment] 2022-03-09 20:00
@oceanByte Thanks, I was just checking here on this issue, too. https://near.academy/near101/chapter-6 looks good to me now, so I'm closing this issue. Thanks.

**Closed as completed by ryancwalsh** 2022-03-09 20:00 UTC
Labels: bug, good first issue

**Comment by amaharana** [comment] 2022-03-09 22:19
Great, thanks!
